### ISSUE TITLE
Occasional junk characters

### ISSUE THREAD

**Issue by zz-fugazi** [prampec/LcdBarGraph#3]
I was getting random junk characters until I added a lcd.clear() call to the constructor, like this:

    _lcd->createChar(1, this->_level1);
    _lcd->createChar(2, this->_level2);
    _lcd->createChar(3, this->_level3);
    _lcd->createChar(4, this->_level4);
    _lcd->clear();	// put lcd back into DDRAM mode

See bperrybap's response at https://forum.arduino.cc/index.php?topic=459931.0 for an explanation.

**Comment by prampec** [comment]
Thank you for sorting this out!
Fixed in release v2.0.1
